### ISSUE TITLE
line 17 #include <Zumo32U4.h>

### ISSUE THREAD

**Issue by dirtclod** [pololu/zumo-32u4-arduino-library#4]
i am new at this sketch for my zumo. when i added this program into ardunio code and did the analyzer it said 'Zumo32U4.h' file not found. will this be ok to down load onto my robot.

**Comment by kevin-pololu** [comment]
It sounds like you didn't have the library installed properly. If you are still having trouble, please post on the [Pololu forum](https://forum.pololu.com/), which is a better place for us to help you troubleshoot.
